name: Test
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install pnpm
        run: npm i -g pnpm@10.2.0
      - name: Install packages
        run: pnpm i
      - name: Prettier
        run: pnpm format:check
      - name: ESLint
        run: pnpm lint
      - name: Test
        run: pnpm test
      - name: Run packaging
        run: pnpm package
